###

POST http://localhost:8080/market/add
content-type: application/json

{
    "kingdomName": "uprzejmy",
    "resource": "food",
    "count": 100,
    "price": 30
}

###

GET http://localhost:8080/kingdom/uprzejmy
content-type: application/json

{
}

###

POST http://localhost:8080/auth/register
content-type: application/json

{
    "username": "123",
    "password": "123"
}

###

POST http://localhost:8080/kingdom/send-carriers
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MzE4MjU5OTgsImlhdCI6MTczMTgyNTM5OCwianRpIjoiMzFmNzMzMjktY2Y4OS00ODE5LWIwNjctYmJmNDA5MjhkNzU5Iiwic3ViIjoidXByemVqbXkifQ.Xdz4WJOGbjZpSITW1d8rLZWCkHYBdfdVKwUAbQ5tbQHePDQP67Xs20hZ_CGMu9eS1_GNyvdPOiij1Tj3hqBm6w

{
    "destinationKingdomName": "BlacksmithBot",
    "resource": "food",
    "amount": 1111
}
