GET http://localhost:8080/
content-type: application/json

###

POST http://localhost:8080/kingdom/
content-type: application/json

{
    "name": "uprzejmy"
}

###

POST http://localhost:8080/market/add
content-type: application/json

{
    "kingdomName": "uprzejmy",
    "resource": "food",
    "count": 100,
    "price": 30
}

###

GET http://localhost:8080/kingdom/uprzejmy
content-type: application/json

{
}

###

POST http://localhost:8080/auth/authenticate
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
