###

POST http://localhost:8080/market/add
content-type: application/json

{
    "kingdomName": "uprzejmy",
    "resource": "food",
    "count": 100,
    "price": 30
}

###

GET http://localhost:8080/kingdom/uprzejmy
content-type: application/json

{
}

###

POST http://localhost:8080/auth/register
content-type: application/json

{
    "username": "123",
    "password": "123"
}

###

POST http://localhost:8080/kingdom/send-carriers
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Mjg0MTk5MzgsImlhdCI6MTcyODQxOTMzOCwianRpIjoiNWQzZDdiYWItMDJjZi00ZmRmLTlkOGUtNThiZGI0NzkxY2I4Iiwic3ViIjoidXByemVqbXkifQ.e2_i8ec77q4-1kbQWEVWrBZQDybqnMjGEhvpKFHbKEMoOdsIgb6G-n0P2ZBs9M6bIqGW3IfSiOFq9uIuVsQYKw

{
    "destinationKingdomName": "uprzejmy",
    "resource": "food",
    "amount": 100
}
